/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as HonorsIndexRouteImport } from './routes/honors/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsIndexRoute = HonorsIndexRouteImport.update({
  id: '/honors/',
  path: '/honors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/honors/': typeof HonorsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/honors': typeof HonorsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/honors/': typeof HonorsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs/$slug'
    | '/blogs/'
    | '/experiences/'
    | '/honors/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blogs/$slug' | '/blogs' | '/experiences' | '/honors' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/blogs/$slug'
    | '/blogs/'
    | '/experiences/'
    | '/honors/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  HonorsIndexRoute: typeof HonorsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors/': {
      id: '/honors/'
      path: '/honors'
      fullPath: '/honors/'
      preLoaderRoute: typeof HonorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  HonorsIndexRoute: HonorsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
